default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: firstblog_development  # Use a unique database name
  username: firstblog
  password: password123
  host: localhost

test:
  <<: *default
  database: firstblog_test  # Use a unique database name for testing
  username: firstblog
  password: password123  # Ensure this is correct
  host: localhost

production:
  <<: *default
  database: firstblog_production  # Use a unique database name for production
  username: firstblog
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Ensure you have this environment variable set
  host: localhost
