default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: new_blog  # Use a unique database name
  username: edward
  password: Nsumba1984&&
  host: localhost

test:
  <<: *default
  database: new_blog   # Use a unique database name for testing
  username: edward
  password: Nsumba1984&&  # Ensure this is correct
  host: localhost

production:
  <<: *default
  database: new_blog    # Use a unique database name for production
  username: edward
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Ensure you have this environment variable set
  host: localhost
